module.exports = {
  APP_NAME: 'Bendita-Comida',

  ROUTES: {
    HOME: '/',
    MENU: '/menu',
    ADMIN: '/admin',
    AUTH_LOGIN: '/auth/login',
    AUTH_LOGOUT: '/auth/logout',
    TESTIMONIOS: '/testimonios',
    INFORMACION_UTIL: '/informacion-util',
  },

  ADMIN_ROUTES: {
    DASHBOARD: '/admin',
    CATEGORIAS: '/admin/categorias',
    CATEGORIAS_CREATE: '/admin/categorias/create',
    PRODUCTOS: '/admin/productos',
    PRODUCTOS_CREATE: '/admin/productos/create',
    PROMOCIONES: '/admin/promociones',
    PROMOCIONES_CREATE: '/admin/promociones/create',
    CONFIGURACION: '/admin/configuracion',
    HERO: '/admin/hero',
    TESTIMONIOS: '/admin/testimonios',
    TESTIMONIOS_CREATE: '/admin/testimonios/create',
    TESTIMONIOS_PENDIENTES: '/admin/testimonios/pendientes',
    INFORMACION_UTIL: '/admin/informacion-util',
    ZONAS_ENTREGA: '/admin/informacion-util/zonas-entrega',
    ZONAS_ENTREGA_CREATE: '/admin/informacion-util/zonas-entrega/create',
    FORMAS_PAGO: '/admin/informacion-util/formas-pago',
    FORMAS_PAGO_CREATE: '/admin/informacion-util/formas-pago/create',
    PREGUNTAS_FRECUENTES: '/admin/informacion-util/preguntas-frecuentes',
    PREGUNTAS_FRECUENTES_CREATE: '/admin/informacion-util/preguntas-frecuentes/create',
    PERFIL: '/admin/perfil',
  },

  SITE: {
    logoUrl: '/images/logo-bendita-comida.png',
    tagline: 'Sabores de casa, calidad premium',
    instagram: 'https://instagram.com/comidacarito',
    instagramHandle: '@comidacarito',
    email: 'hola@comidacarito.com',
    location: 'Buenos Aires, Argentina',
    hours: 'Lun – Sáb · 11:00 a 21:00',
  },
};
